# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 561ff836a4185a7ebba352a693dbef2a73d078beb3eb3195d0a7dc98a972d91ab2e0b1cd64802b6d99350831823dd5a1f97ffd6aefdffbbfa246985412e262da

test:
  secret_key_base: 69b5aea352442fdd19b35695e21e49f1bfce1c9bfc9e268addb713fad01a0a910a6e6f4eec22ca467d8e2a5504d2ae073fc2588601022fb06f999505e31bb375

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
